management:
  server:
    port: 9091
  endpoints:
    web:
      exposure:
        include: health,metrics,doengexperiment
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
        add-additional-paths: true
      group:
        readiness:
          include: readinessState,db

server:
  tomcat:
    mbeanregistry:
      enabled: true

doeng:
  experiment:
    metrics:
      enabled: true
